"""
Jira integration service for TraceAI.
Provides basic issue creation from test cases.
"""

import os
import requests
import json
from typing import Optional, Dict, Any


# Semantic fallbacks tried, in order, when a project has no issue type
# literally named the requested category (e.g. a team-managed project with
# only Epic/Task/Story/Subtask has no "Bug" type). "task" is included last
# in every list as a universally-available generic catch-all.
_CATEGORY_ISSUE_TYPE_ALIASES: Dict[str, list] = {
    "bug": ["defect", "error", "incident", "task"],
    "task": ["task"],
    "story": ["story", "task"],
}


class JiraService:
    """
    Basic Jira Cloud integration for creating issues from test cases.
    
    Requires environment variables:
    - JIRA_BASE_URL: e.g., https://your-domain.atlassian.net
    - JIRA_EMAIL: Email for Jira Cloud authentication
    - JIRA_API_TOKEN: API token for Jira Cloud authentication
    - JIRA_PROJECT_KEY: Project key (e.g., TRACE)
    """
    
    def __init__(self):
        self.base_url = (os.getenv("JIRA_BASE_URL") or "").strip()
        self.email = (os.getenv("JIRA_EMAIL") or "").strip()
        self.api_token = (os.getenv("JIRA_API_TOKEN") or "").strip()
        self.project_key = (os.getenv("JIRA_PROJECT_KEY") or "").strip()
    
    def is_configured(self) -> bool:
        """Check if all required Jira credentials are configured."""
        return bool(self.base_url and self.email and self.api_token and self.project_key)
    
    def get_configuration_status(self) -> Dict[str, Any]:
        """Get the current Jira configuration status."""
        return {
            "configured": self.is_configured(),
            "base_url_set": bool(self.base_url),
            "email_set": bool(self.email),
            "api_token_set": bool(self.api_token),
            "project_key_set": bool(self.project_key),
            "missing": self._get_missing_config(),
        }
    
    def _get_missing_config(self) -> list:
        """Get list of missing configuration items."""
        missing = []
        if not self.base_url:
            missing.append("JIRA_BASE_URL")
        if not self.email:
            missing.append("JIRA_EMAIL")
        if not self.api_token:
            missing.append("JIRA_API_TOKEN")
        if not self.project_key:
            missing.append("JIRA_PROJECT_KEY")
        return missing
    
    def create_issue(
        self,
        test_case: Dict[str, Any],
        requirement_text: str,
        category: str = "Task",
        extra_fields: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """
        Create a Jira issue from a test case.
        
        Args:
            test_case: Test case dictionary with fields like id, description, expected, etc.
            requirement_text: Original requirement text
            category: Issue type in Jira (default: Task)
            extra_fields: Optional additional Jira fields (e.g. reporter) some
                projects require but cannot be inferred from a test case.
        
        Returns:
            Dictionary with success status, issue_key, issue_url, and message
        """
        if not self.is_configured():
            return {
                "success": False,
                "message": "Jira is not configured. Please set environment variables.",
                "missing_config": self._get_missing_config(),
            }
        
        try:
            # Extract test case information
            test_case_id = test_case.get("id", "TC00")
            test_case_type = test_case.get("type", category)
            requirement_id = str(test_case.get("requirement_id") or "R01").strip() or "R01"
            
            # Build test case description from available fields
            description_parts = []
            if test_case.get("description"):
                description_parts.append(test_case["description"])
            elif test_case.get("scenario"):
                description_parts.append(test_case["scenario"])
            elif test_case.get("class"):
                description_parts.append(test_case["class"])
            
            test_case_description = " ".join(description_parts) or "Test case"
            
            # Build issue summary
            summary = f"[{requirement_id}] Test Case {test_case_id}: {test_case_type}"
            
            # Build issue description
            issue_description = f"""Requirement ID:
{requirement_id}

Requirement:
{requirement_text}

Test Case ID:
{test_case_id}

Test Case:
{test_case_description}

Expected Result:
{test_case.get('expected', 'Not specified')}

Category:
{test_case_type}

Generated by TraceAI
"""
            
            # Prepare Jira API payload
            # Jira Cloud's v3 API requires the description as Atlassian
            # Document Format (ADF), not a plain string.
            issue_type_id = self._lookup_issue_type_id(category)
            issuetype_field = {"id": issue_type_id} if issue_type_id else {"name": category}
            fields = {
                "project": {"key": self.project_key},
                "summary": summary,
                "description": _build_adf_description(issue_description),
                "issuetype": issuetype_field,
            }
            if extra_fields:
                fields.update(extra_fields)
            payload = {"fields": fields}
            
            # Make API request
            api_url = f"{self.base_url}/rest/api/3/issue"
            headers = {
                "Authorization": f"Basic {self._encode_credentials()}",
                "Accept": "application/json",
                "Content-Type": "application/json",
            }
            
            response = requests.post(
                api_url,
                json=payload,
                headers=headers,
                timeout=10,
            )
            
            if response.status_code not in (200, 201):
                return self._build_error_response(response)
            
            # Parse response
            response_data = response.json()
            issue_key = response_data.get("key")
            issue_id = response_data.get("id")
            
            if not issue_key:
                return {
                    "success": False,
                    "message": "Jira issue created but no key returned.",
                }
            
            # Build Jira issue URL
            issue_url = f"{self.base_url}/browse/{issue_key}"
            
            return {
                "success": True,
                "issue_key": issue_key,
                "issue_id": issue_id,
                "issue_url": issue_url,
                "message": f"Jira issue created successfully: {issue_key}",
            }
        
        except requests.exceptions.RequestException as e:
            return {
                "success": False,
                "message": f"Network error connecting to Jira: {str(e)}",
            }
        except Exception as e:
            return {
                "success": False,
                "message": f"Error creating Jira issue: {str(e)}",
            }

    def _build_error_response(self, response) -> Dict[str, Any]:
        """Translate a non-2xx Jira response into a specific, actionable message."""
        if response.status_code in (401, 403):
            return {
                "success": False,
                "message": (
                    "Jira authentication failed. Check JIRA_EMAIL and "
                    "JIRA_API_TOKEN."
                ),
                "error_details": response.text,
            }

        if response.status_code == 400:
            field_errors = {}
            error_messages = []
            try:
                body = response.json()
                field_errors = body.get("errors") or {}
                error_messages = body.get("errorMessages") or []
            except ValueError:
                pass

            details = "; ".join(
                [*error_messages, *(f"{field}: {reason}" for field, reason in field_errors.items())]
            )
            return {
                "success": False,
                "message": details or "Jira rejected the request. Check the project key and issue type.",
                "error_details": response.text,
            }

        return {
            "success": False,
            "message": f"Jira API error: {response.status_code}",
            "error_details": response.text,
        }
    
    def _encode_credentials(self) -> str:
        """Encode email and API token for Basic authentication."""
        import base64
        credentials = f"{self.email}:{self.api_token}"
        encoded = base64.b64encode(credentials.encode()).decode()
        return encoded

    def _lookup_issue_type_id(self, category: str) -> Optional[str]:
        """Resolve `category` to the real issue-type ID configured for this
        Jira project.

        Uses the issue-creation metadata endpoint
        (`/issue/createmeta/{project}/issuetypes`) rather than the plain
        project endpoint: Jira Cloud does not reliably surface `issueTypes`
        via `GET /project/{key}` for team-managed ("KAN"-style) projects,
        and the createmeta endpoint is the API Jira itself uses to
        determine which issue types are actually valid to create.

        A team-managed project is not guaranteed to have an issue type
        literally named "Bug" (e.g. a fresh Kanban template only ships
        Epic/Task/Story/Subtask). When the exact name isn't present, this
        falls back to known semantic aliases so "Bug" still resolves to a
        real, creatable issue type instead of being sent as an invalid name.
        Returns None (caller falls back to sending the raw name) only if
        the project's issue types cannot be retrieved at all.
        """
        try:
            response = requests.get(
                f"{self.base_url}/rest/api/3/issue/createmeta/{self.project_key}/issuetypes",
                headers={
                    "Authorization": f"Basic {self._encode_credentials()}",
                    "Accept": "application/json",
                },
                timeout=10,
            )
        except requests.exceptions.RequestException:
            return None

        if response.status_code != 200:
            return None

        try:
            issue_types = response.json().get("issueTypes") or []
        except ValueError:
            return None

        by_name = {
            str(issue_type.get("name", "")).strip().lower(): issue_type.get("id")
            for issue_type in issue_types
        }

        normalized_category = str(category or "").strip().lower()
        if normalized_category in by_name:
            return by_name[normalized_category]

        for alias in _CATEGORY_ISSUE_TYPE_ALIASES.get(normalized_category, []):
            if alias in by_name:
                return by_name[alias]

        return None


def _build_adf_description(text: str) -> Dict[str, Any]:
    """Wrap plain text into the minimal Atlassian Document Format Jira v3 requires."""
    paragraphs = [line for line in text.split("\n") if line.strip()]
    return {
        "type": "doc",
        "version": 1,
        "content": [
            {"type": "paragraph", "content": [{"type": "text", "text": line}]}
            for line in paragraphs
        ] or [{"type": "paragraph", "content": []}],
    }
